name: Deploy DevOps Lambda - vars

on:
  workflow_dispatch:
    inputs:
      environment_name:
        required: true
        default: ""
        type: choice
        options:
        - develop
        - test
        - staging

jobs:
  env-vars:
    runs-on: ubuntu-latest
    environment: ${{inputs.environment_name}}
    outputs:
      s3_bucket: ${{vars.S3BUCKET}}
      stack_name: ${{vars.STACKNAME}}
      aws_region: ${{vars.AWSREGION}}
    steps:
      - run: |
          echo ${{vars.S3BUCKET}}
          echo ${{vars.STACKNAME}}
          echo ${{vars.AWSREGION}}

deploy-lambda:
  name: Deploy ${{inputs.environment_name}}
  needs: env-vars
  permissions:
    id-token: write
    contents: read
  uses: build-sam.yaml
  with:
    s3_bucket: ${{ needs.env-vars.outputs.s3_bucket }}
    stack_name: ${{ needs.env-vars.outputs.stack_name }}
    aws_region: ${{ needs.env-vars.outputs.aws_region }}
    template_file_path: template.yaml
    environment_name: ${{inputs.environment_name}}
  secrets: inherit